import { Box, ChakraProvider, Divider, Heading, HStack, Stack, Text, theme } from "@chakra-ui/react";
import Head from "next/head";
import { Board } from "../Board";

export default function NotFound(){
    return (
        <div>
            <ChakraProvider theme={theme}>
                <Box bg="gray.100">
                    <Head>
                        <title>404 - Página não encontrada</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>

                    <HStack w="100vw" h="100vh" alignItems="center" justifyContent="center">
                        
                        <HStack borderRadius="4" bg="white" p="8" boxShadow="sm" spacing="8">
                            <Heading color="gray.600">404</Heading>
                            
                            <Box h="50px" w="2px" bg="red.400"/>

                            <Stack>
                                <Heading color="gray.800">Página não contemplada</Heading>
                                <Text color="gray.600">Infelizmente, não existe nenhum conteúdo acessando esse endereço.</Text>
                            </Stack>
                        </HStack>
                        
                    </HStack>
                </Box>
            </ChakraProvider>
        </div>
    )
}